tide_character_icon ❯
tide_character_vi_icon_default ❮
tide_character_vi_icon_replace ▶
tide_character_vi_icon_visual V
tide_cmd_duration_icon
tide_git_icon
tide_jobs_icon 
tide_private_mode_icon 󰗹
tide_prompt_icon_connection ' '
tide_pwd_icon
tide_pwd_icon_unwritable 
tide_status_icon ✔
tide_status_icon_failure ✘
tide_vi_mode_icon_default D
tide_vi_mode_icon_insert I
tide_vi_mode_icon_replace R
tide_vi_mode_icon_visual V
